### ISSUE TITLE
More in-depth security discussion of EMRFS AssumeRole support

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/amazon-emr-management-guide#10]
It's unclear to me in the documentation today what the security model for EMRFS `AssumeRole` is. As far as I've been able to gather, the node running a task will transparently call `AssumeRole` on your behalf if you request a certain prefix or match a user pattern.

However, this seems more like a convenience mechanism than a strong security one (i.e., there's no mechanism in place to stop a task from hitting an S3 bucket with the instance credentials or another assumeable role). Is that correct? It seems worth spelling out more explicitly in the documentation to make people don't use it in an attempt to make security boundaries.

**Comment by Pahtoe** [comment]
@copumpkin Hey Daniel, there was an omission in this content. We neglected to point out that the EC2 instance profile and each role that EMRFS assumes need to have permissions for AssumeRole in a trust policy. We added a section to the HTML version of doc the other day here: https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-emrfs-iam-roles.html#emr-emrfs-iam-roles-role-configuration I'm in process of updating here on Github now. LMK if this addresses your concern. Thanks for being patient...sorry for the delay.

**Comment by joelthompson** [comment]
Hi @Pahtoe -- I'm a bit confused by this. Based on the documentation, looks like there's a circular relationship between the two roles? That is, the trust policy for `EMRFSRole_First` and `EMRFSRole_Second` allows `EMR_EC2_DefaultRole` to assume those roles, and `EMR_EC2_DefaultRole` allows `EMRFSRole_First` and `EMRFSRole_Second` to assume it? So one could just continually AssumeRole from one to the other?

**Comment by Pahtoe** [comment]
@joelthompson I'm looking into this. I think there may be a misstatement in the guide but want to confirm.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
