### ISSUE TITLE
Guide to creating cross-realm trust between EMR and AWS Managed AD

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/amazon-emr-management-guide#13]
I'm having a lot of trouble getting the finicky details working properly to connect an EMR in my account to an AWS Managed Microsoft AD in the same account. In theory all the various knobs are in place, but a step-by-step guide would be pretty nice, especially if it included an overview of `aws-cli` or the relevant API calls, to ease automation.

It's complicated a bit by the fact that the managed AD doesn't let you run the commands described [here](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-kerberos-cross-realm.html#emr-kerberos-ad-configure-trust) on it, like `netdom trust EC2.INTERNAL /Domain:ad.domain.com /add /realm /passwordt:MyVeryStrongPassword`, and instead exposes the trust machinery through an AWS API.

**Comment by Pahtoe** [comment]
@copumpkin When you say "connect an EMR in my account," do you mean to authenticate EMR cluster users to EMR using AWS Managed AD using Kerberos? If so, this isn't supported at present. Sorry for the inconvenience. There's a note about that here: https://github.com/awsdocs/amazon-emr-management-guide/blob/master/doc_source/emr-kerberos.md

**Comment by copumpkin** [comment]
Oh, that's disappointing 😦 I hadn't seen that note
