### ISSUE TITLE
Document Required KMS Permissions

### ISSUE THREAD

**Issue by joelthompson** [awsdocs/amazon-emr-management-guide#14]
This is a bit similar to #9 but not fully included in it -- https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-encryption-enable.html states:

> The role for the Amazon EC2 instance profile must have permissions to use the CMK you specify.

However, it doesn't actually specify what those permissions are. It then states:

> You can use the AWS Management Console to add your instance profile or EC2 instance profile to the list of key users for the specified AWS KMS CMK, or you can use the AWS CLI or an AWS SDK to attach an appropriate key policy.

It then walks through going through the AWS console to add the role as a "Key User" but it doesn't actually specify what the required permissions are, nor does it ever describe how one would use the AWS CLI or an AWS SDK to grant appropriate permissions. Can the required KMS permissions please be documented so we can more easily manage them in code?

Thanks!

**Comment by Pahtoe** [comment]
Got it. Will get it in.

**Comment by ARentz07** [comment]
Is there any update on this? I've been advised not to use the default roles and have admittedly been exercising a trial-and-error strategy to figure out what I actually need for my cluster to function.

**Comment by Pahtoe** [comment]
Apologies for not closing this out. The question re: what permissions does EMR_EC2_DefaultRole (or a custom role) need to be a CMK encryption key user is answered in the KMS documentation. It's under setting up key users here under the heading "Allows key users to use the CMK" in [Default Key Policy](https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html#key-policy-default). Also, following the procedure in the EMR guide to add a key user, you can switch to "Policy view" at https://console.aws.amazon.com/kms to see the specific permissions. Those are as follows and reflect what's in the doc above. The doc also provides descriptions of what each allowed action is.
`{
            "Sid": "Allow use of the key",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::MyAcctID:role/EMR_EC2_DefaultRole"
                ]
            },
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:DescribeKey"
            ],
            "Resource": "*"
        },
        {
            "Sid": "Allow attachment of persistent resources",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::MyAcctID:role/EMR_EC2_DefaultRole"
                ]
            },
            "Action": [
                "kms:CreateGrant",
                "kms:ListGrants",
                "kms:RevokeGrant"
            ],
            "Resource": "*",
            "Condition": {
                "Bool": {
                    "kms:GrantIsForAWSResource": "true"
                }
            }
        }`
