### ISSUE TITLE
Document required connectivity for LocalDiskEncryptionKeyProvider type AwsKms

### ISSUE THREAD

**Issue by joelthompson** [awsdocs/amazon-emr-management-guide#15]
https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-create-security-configuration.html and https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-encryption-enable.html#emr-awskms-keys discuss using KMS CMKs for EMR encryption. However, there is no mention that the main EC2 instances themselves require network connectivity to KMS when using AwsKms for the local disk encryption (either over the internet or over a VPC Endpoint). Having this spelled out explicitly would be helpful.

**Comment by Pahtoe** [comment]
@joelthompson Excellent catch. We'll spell this out in an upcoming edit.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
