### ISSUE TITLE
Encryption At Rest Options Seem to Work on HA Masters

### ISSUE THREAD

**Issue by joelthompson** [awsdocs/amazon-emr-management-guide#17]
https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-ha-applications.html#emr-plan-ha-features-unsupported states:

```
The following EMR features are currently not available in an EMR cluster with multiple master nodes:
...
* At-rest and in-transit encryption options
```

However, I successfully spun up a multi-master EMR cluster with encryption-at-rest options. I even terminated the active master node (at least, the active Yarn RM node) and a new one replaced it and re-applied the encryption at rest options.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
