### ISSUE TITLE
HA Supported Applications and Features Page Contains an en-dash instead of a normal dash

### ISSUE THREAD

**Issue by joelthompson** [awsdocs/amazon-emr-management-guide#18]
I would PR this in, but the docs haven't been ported here yet :)

https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-ha-applications.html#emr-plan-ha-applications-HDFS states:

```
If you need to find out which NameNode is active, you can use SSH to connect to any master node in the cluster and run the following command:

hdfs haadmin –getAllServiceState
```

If you stare closely, the character before "getAllServiceState" is an en-dash (`–`) rather than a normal dash (`-`). If you try to copy/paste it into a command-line window, you get this:

```
$ hdfs haadmin –getAllServiceState
Bad command '–getAllServiceState': expected command starting with '-'
...
```

If you replace the `–` with a `-` it works just fine:

```
$ hdfs haadmin -getAllServiceState
ip-XX-XX-XX-XX.ec2.internal:8020                  active    
ip-XX-XX-XX-XX.ec2.internal:8020                  standby
```

**Comment by Pahtoe** [comment]
Thanks @joelthompson. There may be something hinky in our transform here. It looks like it's not an endash in our source. May need to track this down through our build system.

**Comment by joelthompson** [comment]
Looks fixed now, thanks!
