### ISSUE TITLE
Write data to an Amazon S3 bucket you don't own using Spark

### ISSUE THREAD

**Issue by drorata** [awsdocs/amazon-emr-management-guide#21]
In https://github.com/awsdocs/amazon-emr-management-guide/blob/master/emr-s3-acls.md you discuss how to work with canned ACLs. I'm facing this issue when working with Spark. Can you explain in the documentation how to set `fs.s3.canned.acl` (to `BucketOwnerFullControl` for example) from a Spark application written in Java?

**Comment by Pahtoe** [comment]
@drorata Sorry for the miss. Not exactly using Spark, so not sure if this is useful in your application, but you should be able to set the property using the `core-site` configuration classification. There's an example of how to set property values using a configuration classification here. https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-configure-apps-create-cluster.html#emr-configure-apps-create-cluster-sdk In that example, the `hive-site` configuration classification is used to set a couple hive-specific values.  I found this StackOverflow post re: setting the value from within Spark. Hope this helps. Good suggestion to add to doc's and we'll add to our queue.

**Comment by drorata** [comment]
Thanks for the additional details. I am trying to configure/control the behavior from the Java(!) code directly and preferring not to change `core-site`. 

I tried:

```java
spark.sparkContext().hadoopConfiguration().set("fs.s3.canned.acl","BucketOwnerFullControl");
```

where `spark` is an instance of `SparkSession`. It didn't seem to help. Did I miss something? Should I expect the above line to solve the problem?

**Comment by RaymondHsu** [comment]
I also run into the issue with my python spark driver program.  After many tries and errors, found the easiest way is to set it up in hadoop configuration.  The tricky thing is that, in hadoop configuration, the property name is actually "fs.s3.acl.default" instead.  Just set it to "BucketOwnerFullControl".  You may also want to set it up for "s3a", and "s3n" too.  See Apache hadoop document [here](https://hadoop.apache.org/docs/current/hadoop-aws/tools/hadoop-aws/index.html)  There is another useful [posting](https://www.richakhandelwal.com/cross-account-s3-transfer-policy/)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
