### ISSUE TITLE
The link to CloudWatch evcents type is broken.

### ISSUE THREAD

**Issue by btower-labz** [awsdocs/amazon-emr-management-guide#22]
There is a broken link **Amazon EMR Events** at the bottom: https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-manage-cloudwatch-events.html

The source: https://github.com/awsdocs/amazon-emr-management-guide/blob/master/doc_source/emr-manage-cloudwatch-events.md

Please update that link.

**Comment by Pahtoe** [comment]
Fixed
