### ISSUE TITLE
Incorrect instance type recommendation 

### ISSUE THREAD

**Issue by ervansetiawan-tr** [awsdocs/amazon-emr-management-guide#31]
The documentation at https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-instances-guidelines.html does not match the content in this repo and there seems to be a typo in the live documentation around the recommended instance type. 

"The master node does not have large computational requirements. For most clusters of 50 or fewer nodes, consider using an m5.xlarge instance. For clusters of more than 50 nodes, consider using an m4.xlarge."

I think it should have been 
"The master node does not have large computational requirements. For most clusters of 50 or fewer nodes, consider using an m5.large instance. For clusters of more than 50 nodes, consider using an m5.xlarge."

**Comment by ellkend-aws** [comment]
@ervansetiawan-tr Thank you for bringing this to our attention. We recently updated the [Cluster Configuration Guidelines and Best Practices](https://docs.aws.amazon.com/en_us/emr/latest/ManagementGuide/emr-plan-instances-guidelines.html) topic to address this and other related issues. The changes will be picked up by the GitHub version of our guide shortly.
