### ISSUE TITLE
I believe s3:HeadBucket is not a valid IAM action

### ISSUE THREAD

**Issue by ghost** [awsdocs/amazon-emr-management-guide#33]
In [emr-iam-role-for-ec2.md](https://github.com/awsdocs/amazon-emr-management-guide/blob/master/doc_source/emr-iam-role-for-ec2.md), `s3:HeadBucket` is suggested.

According to [IAM UserGuide list for S3](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazons3.html) and [S3 HeadBucket API documentation](https://docs.aws.amazon.com/en_us/AmazonS3/latest/API/API_HeadBucket.html), the corresponding IAM action we need here is `s3:ListBucket`.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
