### ISSUE TITLE
Github docs are out of date compared to published AWS docs

### ISSUE THREAD

**Issue by Tyrone321** [awsdocs/amazon-emr-management-guide#38]
The last commit was Jan 2020. The Github docs are way out of date with the published EMR documentation.

Has Github been deprecated as a repo for documentation?

**Comment by Pahtoe** [comment]
@Tyrone321 thanks for calling attention to this. I'll get it fixed ASAP.

**Comment by Pahtoe** [comment]
Fixed now. Thanks again!
