### ISSUE TITLE
Wrong explanation

### ISSUE THREAD

**Issue by advancedluke** [awsdocs/amazon-emr-management-guide#39]
"consider using an m4.xlarge, because vCores in m4.xlarge are twice that of m5.xlarge" on http://docs.aws.amazon.com/en_us/emr/latest/ManagementGuide/emr-plan-instances-guidelines.html

should change "consider using an m5.xlarge, because vCores in m5.xlarge are twice that of m5.large"

**Comment by ellkend-aws** [comment]
@advancedluke Thank you for bringing this to our attention. We recently updated the [Cluster Configuration Guidelines and Best Practices](https://docs.aws.amazon.com/en_us/emr/latest/ManagementGuide/emr-plan-instances-guidelines.html) topic in the EMR Management Guide to address this and other related issues.
