### ISSUE TITLE
How to update the emr master dns whenever the cluster terminates

### ISSUE THREAD

**Issue by newtoworld999** [awsdocs/amazon-emr-management-guide#40]
Hi 
In case we terminate the emr cluster and spinup the new one within a vpc, a differnt ip address and the dns for the master node, resource manager and all gets changed. Inorder to have a friendly name name and also to point the current running emr cluster i see below document 
https://aws.amazon.com/blogs/big-data/dynamically-create-friendly-urls-for-your-amazon-emr-web-interfaces/
We are using our on prem DNS and apart from this we cannot have any other way? If we create a vpc endpoint to emr cluster and do the dns alias to the vpc endpoint that will not solve the purpose?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
