### ISSUE TITLE
EMR `Consistent View` not relevant anymore

### ISSUE THREAD

**Issue by praveensripati** [awsdocs/amazon-emr-management-guide#41]
Now that S3 is strongly consistency by default across regions.

Amazon S3 Update – Strong Read-After-Write Consistency
https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/

The below EMR documentation is not relevant anymore.
https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-consistent-view.html

Changes have to be done to the EMR documentation to reflect the same.

**Comment by ellkend-aws** [comment]
@praveensripati  Thank you for bringing this to our attention. The team has recently updated our topic on Consistent View for Amazon EMR to note that you no longer need to use EMRFS Consistent View as Amazon S3 supports Strong Read-After-Write Consistency.
