### ISSUE TITLE
access denied spark emr -> s3 

### ISSUE THREAD

**Issue by geofflangenderfer** [awsdocs/amazon-emr-management-guide#49]
[the instructions here lead to an access denied](https://github.com/awsdocs/amazon-emr-management-guide/blob/main/doc_source/emr-gs.md) when calling s3.

I assume we need to add some bucket/iam policy to the s3 bucket to get a success

I've been reading through docs on iam/bucket policies for a couple hours with little progress. 

Any pointers?

**Comment by ellkend-aws** [comment]
@geofflangenderfer Thank you for telling us about this issue. A member of the team will be working on it and will provide updates here about progress.

**Comment by ellkend-aws** [comment]
@geofflangenderfer - After looking into this issue, we've been unable to determine the specific cause of the S3 access issue that you described. I suggest that you post your question on AWS re:Post (https://repost.aws/) with additional details about your setup to help troubleshoot.
