### ISSUE TITLE
Information on essential EC2 node IAM permissions

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/amazon-emr-management-guide#9]
The management guide has a [fairly extensive guide to IAM permissions](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-iam-roles.html) (including sub-pages of that), but as far as I can tell, seems to be lacking a fairly important piece of information: what EMR nodes actually _need_ to do their job, independent of tasks running on top of them.

Right now the guidance seems to be roughly, "use the `arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role` managed policy, or you can customize your permissions, especially as it pertains to a security configuration that configures `AssumeRole` for EMRFS".

But `arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role` is actually pretty powerful:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Resource": "*",
            "Action": [
                "cloudwatch:*",
                "dynamodb:*",
                "ec2:Describe*",
                "elasticmapreduce:Describe*",
                "elasticmapreduce:ListBootstrapActions",
                "elasticmapreduce:ListClusters",
                "elasticmapreduce:ListInstanceGroups",
                "elasticmapreduce:ListInstances",
                "elasticmapreduce:ListSteps",
                "kinesis:CreateStream",
                "kinesis:DeleteStream",
                "kinesis:DescribeStream",
                "kinesis:GetRecords",
                "kinesis:GetShardIterator",
                "kinesis:MergeShards",
                "kinesis:PutRecord",
                "kinesis:SplitShard",
                "rds:Describe*",
                "s3:*",
                "sdb:*",
                "sns:*",
                "sqs:*",
                "glue:CreateDatabase",
                "glue:UpdateDatabase",
                "glue:DeleteDatabase",
                "glue:GetDatabase",
                "glue:GetDatabases",
                "glue:CreateTable",
                "glue:UpdateTable",
                "glue:DeleteTable",
                "glue:GetTable",
                "glue:GetTables",
                "glue:GetTableVersions",
                "glue:CreatePartition",
                "glue:BatchCreatePartition",
                "glue:UpdatePartition",
                "glue:DeletePartition",
                "glue:BatchDeletePartition",
                "glue:GetPartition",
                "glue:GetPartitions",
                "glue:BatchGetPartition",
                "glue:CreateUserDefinedFunction",
                "glue:UpdateUserDefinedFunction",
                "glue:DeleteUserDefinedFunction",
                "glue:GetUserDefinedFunction",
                "glue:GetUserDefinedFunctions"
            ]
        }
    ]
}
```

Basically, it can do _anything_ to S3, SNS, SQS, SDB, DynamoDB, and several other potentially scary things.

So if you don't fully trust your EMR tasks not to delete/corrupt all your S3 buckets and Dynamo tables, you probably want to customize that policy. But the documentation doesn't make a clear distinction between what EMR itself _needs_ and some speculative permissions on what tasks running on top of it might want.

As far as I've been able to tell, these are completely unused by EMR itself:

* DynamoDB
* SDB
* Kinesis

And S3 is at least partially used to upload logs to the configured logging bucket. Of course, if I tell my EMR job to fetch from s3://foo/bar, I'll need to also include permissions for that in my policy, but that separation is not very crisp right now.

It's also very hard for me to assess whether SNS/SQS is used internally by EMR today because both services have cross-account support so even if I see no relevant queues or topics in my account, I can't say with confidence that I'm not hobbling some uncommon EMR feature by not granting EMR access to those services.

The best experiment I've been able to run is to put the whole thing in a private subnet with no internet access and an S3 VPCE to send logs to S3. The EMR cluster seems quite content in that scenario, which suggests to me that everything but S3 is optional. But obviously if I were to tell an EMR package to fetch from Glue, that would break.

Ultimately, it would be nice to have a broken down table in the documentation saying things like (e.g.,) :

* You always need S3 PutObject and ListBucket powers over your configured logging prefix.
* If you want to use our Glue integration, you need permissions X, Y, Z on the instance IAM role
* If you want to use our EMRFS AssumeRole powers, you need to grant AssumeRole powers to the instance IAM role

Or absent that (but this isn't a documentation thing), a cleaner separation between "task powers" and "EMR machinery powers" like what we have in ECS.

**Comment by copumpkin** [comment]
From what I can tell, older versions of the documentation had a bit more information about this:

https://web.archive.org/web/20140927174314/http://docs.aws.amazon.com:80/ElasticMapReduce/latest/DeveloperGuide/emr-iam-roles-custom.html

mentions

> The access to Amazon SimpleDB is included to permit debugging from the console. Access to CloudWatch is included so the cluster can report metrics. Amazon SNS and Amazon SQS permissions are included for messaging.

It's not clear if the "messaging" is used by EMR or by applications, but the SDB point is pretty clear, and makes me think that if I try to use the EMR debugging functionality it'll fail unless I enable SDB in the policy.

**Comment by copumpkin** [comment]
I also just noticed that EMR is creating SQS queues in my account which I think are used by the state pusher script. But since it seems to support running just fine in a private subnet without SQS private endpoints (which don't exist), the queue doesn't seem essential.

**Comment by Pahtoe** [comment]
This is excellent feedback @copumpkin and a great suggestion for that table breakdown. It might take me a while, but let me do some investigation and fact gathering with the service team

**Comment by copumpkin** [comment]
Thank you @Pahtoe, I look forward to seeing it. I found another example of something that makes me uneasy in the docs (just because it's too broad, tbc):

(emphasis mine)

> Debugging requires the use of roles; your service role and instance profile must allow you to use **all Amazon SQS API operations**. If your roles are attached to Amazon EMR managed policies, you do not need to do anything to modify your roles. **If you have custom roles, you need to add sqs:* permissions**. For more information, see Configure IAM Roles for Amazon EMR Permissions to AWS Services.

From [here](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-debugging.html#emr-plan-debugging-info)

I'm guessing this is because although the debugging SQS queue is created automatically, EMR might also create some sort of EMRFS inconsistency queue if requested, so it wants the `sqs:CreateQueue` power as well? If your table could include a more detailed breakdown of how the SQS permissions are used as well, that would be awesome. It seems less than ideal for anyone running an EMR task to be able to spam all existing queues, or delete them, or consume messages from unrelated queues, etc.

Anyway, thanks again!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
